# The URL the site will be built for
base_url = "https://profs.etsmtl.ca/agruson/"
title = "Adrien Gruson"
default_language = "en"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Do not change the path
[slugify]
paths = "off"

[extra]
# Put all your custom variables here
old_website = false
name = "Adrien Gruson"
job_title = "Assistant Professor at École de technologie supérieure"
job_departement = [["Software and Information Technology Engineering Dept.", "https://www.etsmtl.ca/ets/gouvernance/decanats-et-departements/departement-genie-logiciel-ti"]]
interests = ["Light transport simulation", "Markov Chain Monte Carlo", "Gradient-domain rendering", "Machine learning" ]
education = [["PhD in Computer Graphics, 2015", "Rennes 1 University"], 
	["Master 2 in Computer Research, Major Computer Research, 2011", "Rennes 1 University"], 
	["Eng. Rennes 1 University certificate (option Computer Graphics), 2011", "ESIR, Rennes 1 University"]]
biography = """
I am an Assistant Professor at [École Supérieure de Technologie (ÉTS)](https://www.etsmtl.ca/) in the department of [Information and Communications Technologies](https://www.etsmtl.ca/en/research/Research-innovation/Information-communications-technologies) since September 2021, where I am a member of [the Multimedia Lab](https://en.etsmtl.ca/unites-de-recherche/labmultimedia/accueil?lang=en-CA). 

<div class="alert alert-primary" role="alert">I am actively looking for multiple Master/Ph.D. students who have a strong interest in computer graphics, particularly in rendering. If you are interested in working with me, please first read this <a href="students">page</a> containing additional important information. Then, please send me an email mentioning you read this page and stating your interests in computer graphics. If you have any questions, don't hesitate to reach out to me.</div>

<h3>Current Students</h3>
<ul>
    <li style="font-size:90%">Hassan-Walid Boulerhcha, Undergraduate MITACS Globalinks (intern)</li>
    <li style="font-size:90%">Haolun Ma, Undergraduate MITACS Globalinks (intern)</li>
    <li style="font-size:90%">Justin Benoist, Undergraduate (intern)</li>
	<li style="font-size:90%">Daniel Milenov Milanov, MASc (co-supervised with Sheldon Andrew)</li>
	<li style="font-size:90%">Marc Haraoui, M. Ing (co-supervised with Marco Pedersoli) - CAE</li>
</ul>

<h3>Past Students</h3>
<ul>
	<li style="font-size:90%">Benjamin Boineau, M. Ing (co-supervised with Sheldon Andrew) - Depix</li>
</ul>

<h3>Bio</h3>
Adrien Gruson was a post-doc researcher at McGill University and The University of Tokyo under the supervision of Profs <a href="http://www.cim.mcgill.ca/~derek/">Nowrouzezahrai]</a> and <a href="http://www.ci.i.u-tokyo.ac.jp/~hachisuka/">Hachisuka</a>. He was also a member of the <a href="http://jfli.cnrs.fr/">Japanese French Laboratory of Informatics (JFLI)</a>. His research interests include physically-based rendering, using advance sampling techniques such Markov-chain Monte Carlo, gradient-based estimators.

<h3>Research Fundings</h3>
<ul>
	<li style="font-size:90%">MITACS Acceleration and Globalkinks</li>
	<li style="font-size:90%">NSERC, Discovery, 2022 to present</li>
	<li style="font-size:90%">ÉTS, startup grant, 2021 to present</li>
</ul>

<h3>Course</h3>

- MTI882: Rendu photoréaliste (A2022)
	- <a href="competition/">Results rendering competition</a>
- LOG750: Infographie (H2022, H2023)

"""
websites = [
	{ name = "Adrien Gruson", url = "https://profs.etsmtl.ca/agruson/"},
	{ name = "Damien Rioux-Lavoie", url = "https://riouxld21.github.io/research/" },
	{ name = "Joey Litalien", url = "https://joeylitalien.github.io/" },
	{ name = "Toshiya Hachisuka", url = "https://cs.uwaterloo.ca/~thachisu/" },
	{ name = "Rex West", url = "http://cv.rexwe.st/" },
	{ name = "Luis Gamboa", url = "https://lc.fie.umich.mx/~legg/" },
	{ name = "Derek Nowrouzezahrai", url = "http://www.cim.mcgill.ca/~derek/" },
	{ name = "Iliyan Georgiev", url = "http://iliyan.com/" },
	{ name = "Luisa F. Polania", url = "https://sites.google.com/site/polanialuisa/" },
	{ name = "Nicolas Vibert", url = "http://nicolas-vibert.me/" },
	{ name = "Wojciech Jarosz", url = "https://cs.dartmouth.edu/~wjarosz/" },
	{ name = "Binh-Son Hua", url = "https://sonhua.github.io/" },
	{ name = "Matthias Zwicker", url = "https://www.cs.umd.edu/~zwicker/" },
	{ name = "Elmar Eisemann", url = "https://graphics.tudelft.nl/~eisemann/" },
	{ name = "Jamorn Sriwasansak", url = "http://jamorn.me/" },
	{ name = "Mickael Ribardiere", url = "https://mribar03.bitbucket.io/" },
	{ name = "Martin Sik", url = "https://cgg.mff.cuni.cz/~sik/" },
	{ name = "Jiri Vorba", url = "https://cgg.mff.cuni.cz/~jirka/" },
	{ name = "Remi Cozot", url = "http://cozot.free.fr/" },
	{ name = "Kadi Bouatouch", url = "https://www.irisa.fr/frvsense/Kadi.Bouatouch/" },
	{ name = "Jaroslav Krivanek", url = "https://cgg.mff.cuni.cz/~jaroslav/" },
	{ name = "Sumanta Pattanaik", url = "http://www.cs.ucf.edu/~sumant/" },
	{ name = "Stavros Diolatzis", url = "https://www-sop.inria.fr/members/Stavros.Diolatzis/" },
	{ name = "Wenzel Jakob", url = "http://rgl.epfl.ch/people/wjakob/"},
	{ name = "George Drettakis", url = "http://www-sop.inria.fr/members/George.Drettakis/"},
	{ name = "Keven Villeneuve", url = "https://kevenv.github.io/" },
	{ name = "Gurprit Singh", url = "https://sampling.mpi-inf.mpg.de/"},
	{ name = "Corentin Salaun", url = "https://iribis.github.io/" },
	{ name = "Ege Ciklabakkal", url = "https://cs.uwaterloo.ca/~meciklab/" }
]